---

### Defines the tags for EC2 Instance
Owner: "Vikram@gmail.com"
Manager: "Dave@c.com"
env: DEV_WebServer_R1
resource_name: "{{ env }}"

# Subnet, network, vpc, settings.
ec2_instance_type: t2.micro
ec2_subnet_ids: subnet-c209f58a
ec2_image_bare: ami-faea3480


# Security Groupsg_1
sg_1: sg-a17533d1
sg_2: sg-af4c50d0

#VPC
vpc_id: vpc-4bad8c2d

# availability zones
availability_zone_1: us-east-1a



instance_tags: { "Name": "{{ resource_name }}",
                 "Env": "{{ env }}",
                 "Manager": "{{ Manager }}",
                 "Owner": "{{ Owner }}",
                }
# region
region: us-east-1

