---
# ---------------------------------
# PLAY 1 - create EC2 with base AMI
# ---------------------------------
- name: Create Base AMI
  hosts: localhost
  gather_facts: yes
  vars_files:
    - "group_vars/vars.yml"

  tasks:
  - name: Create Base EC2 Instance
    ec2:
     instance_type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image_bare }}"
     ec2_region: "{{ region }}"
     wait: yes
     instance_tags: "{{ instance_tags  }}"
     group_id: [ "{{ sg_1 }}", "{{ sg_2 }}" ]
     vpc_subnet_id: "{{ ec2_subnet_ids }}"
     assign_public_ip: yes
     exact_count: 1
     count_tag:
      Name: "{{ resource_name }}"
#    register: temp_ec2

  - name: Search ec2
    ec2_remote_facts:
     filters:
      "tag:Name": "{{resource_name}}"
     region: "{{ region }}"
    register: temp_ec2    

  - name: display ec2
    debug: msg="Newly created ec2 - {{ temp_ec2.instances[0]['private_ip_address'] }}"

#  - pause: seconds=120

#  - name: Wait for SSH to come up on " {{ temp_ec2.instances[0]['private_ip'] }} "
#    wait_for: host= "{{ temp_ec2.instances[0]['private_ip'] }}" port=22 delay=60 timeout=320 state=started

  - name: Add all instance private  IPs to host group
    add_host: name="{{ temp_ec2.instances[0]['private_ip_address'] }}" groups=webserver

# --------------------------------
# Play 2 - install pre-reqs to EC2
# -------------------------------
- name: install Pre-req
  hosts: webserver
  become: true
  tasks:
  - name: install the latest version of Apache
    yum: name=httpd.x86_64 state=latest

  - name: start the httpd service
    service: name=httpd state=started

  - name: Create user
    user: name=vsaraf00c group=ec2-user


#------------------------------------
# Play 3 : Create AMI from this image
# -----------------------------------



