---

### Defines the tags for EC2 Instance
Owner: "Vikram@gmail.com"
Manager: "Dave@c.com"
# Modify below fo each release
env: DEV_WebServer_R1
resource_name: "{{ env }}"
base_ami_type: "{{ env }}_AMI"
resource_name_AMI: "{{ env }}_AMI-{{ timestamp }}"


# Change this every 3 months with latest IT provided Image
ec2_image_bare: ami-faea3480

# Change below  everytime you create BASE Image
# Not needed as this is now dynamic. ec2_image: ami-1c3ae466

#-------
## DONOT Modify below entries
##------

# Subnet, network, vpc, settings.
ec2_instance_type: t2.micro
ec2_subnet_ids: subnet-c209f58a


# Security Groupsg_1
sg_1: sg-a17533d1
sg_2: sg-af4c50d0

#VPC
vpc_id: vpc-4bad8c2d

# availability zones
availability_zone_1: us-east-1c    # Not used anywhere



instance_tags: { "Name": "{{ resource_name }}",
                 "Env": "{{ env }}",
                 "Manager": "{{ Manager }}",
                 "Owner": "{{ Owner }}",
                }

AMI_instance_tags: { "Name": "{{ resource_name_AMI }}",
                 "Env": "{{ env }}",
                 "Manager": "{{ Manager }}",
                 "Owner": "{{ Owner }}",
                }

# region
region: us-east-1

